CREATE DATABASE ControleEstoqueGestaoAtivos;
GO

USE ControleEstoqueGestaoAtivos;
GO

CREATE TABLE CategoriaAtivos (
	Id SMALLINT NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(15) NOT NULL
);
GO

CREATE TABLE Filial (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL
);
GO

CREATE TABLE Departamento (
	Id SMALLINT NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(60) NOT NULL
);
GO

CREATE TABLE Cargo (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(60) NOT NULL
);
GO

CREATE TABLE Colaborador (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	IdCargo INTEGER NOT NULL,
	IdDepartamento SMALLINT NOT NULL,
	IdFilial INTEGER NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	CPF CHAR(11) NOT NULL UNIQUE,
	FOREIGN KEY(IdCargo) REFERENCES Cargo(Id),
	FOREIGN KEY(IdDepartamento) REFERENCES Departamento(Id),
	FOREIGN KEY(IdFilial) REFERENCES Filial(Id)
);
GO

CREATE TABLE Perfil (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(80) NOT NULL,
	Descricao VARCHAR(300) NOT NULL
);
GO

CREATE TABLE Usuario (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE,
	SenhaHash VARCHAR(255) NOT NULL,
	Ativo BIT NOT NULL
);
GO

CREATE TABLE UsuarioPerfil (
	IdUsuario INTEGER NOT NULL,
	IdPerfil INTEGER NOT NULL,
	PRIMARY KEY(IdUsuario, IdPerfil),
	FOREIGN KEY(IdUsuario) REFERENCES Usuario(Id),
	FOREIGN KEY(IdPerfil) REFERENCES Perfil(Id)
);
GO

CREATE TABLE Fornecedor (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Fabricante (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
);
GO

CREATE TABLE CategoriaMaterial (
	Id SMALLINT NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(30) NOT NULL
);
GO

CREATE TABLE LocalArmazenamento (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(40) NOT NULL
);
GO

CREATE TABLE Material (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	IdCategoriaMaterial SMALLINT NOT NULL,
	IdFornecedor INTEGER NOT NULL,
	IdFabricante INTEGER NOT NULL,
	IdLocalArmazenamento INTEGER NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	UnidadeMedida VARCHAR(15) NOT NULL,
	EstoqueAtual SMALLINT NOT NULL,
	EstoqueMinimo SMALLINT NOT NULL,
	EstoqueMaximo SMALLINT NOT NULL,
	FOREIGN KEY(IdCategoriaMaterial) REFERENCES CategoriaMaterial(Id),
	FOREIGN KEY(IdFornecedor) REFERENCES Fornecedor(Id),
	FOREIGN KEY(IdFabricante) REFERENCES Fabricante(Id),
	FOREIGN KEY(IdLocalArmazenamento) REFERENCES LocalArmazenamento(Id)
);
GO

CREATE TABLE StatusAtivo (
	Id SMALLINT NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(30) NOT NULL
);
GO

CREATE TABLE AtivosTi (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	IdColaboradorResponsavel INTEGER,
	IdCategoriaAtivos SMALLINT NOT NULL,
	IdFabricante INTEGER NOT NULL,
	IdFornecedor INTEGER NOT NULL,
	IdStatusAtivo SMALLINT NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	CodigoPatrimonio VARCHAR(100) NOT NULL UNIQUE,
	NumeroSerie VARCHAR(100) UNIQUE,
	DataAquisicao DATE NOT NULL,
	ValorAquisicao DECIMAL(10,2) NOT NULL,
	DataFimGarantia DATE,
	FOREIGN KEY(IdColaboradorResponsavel) REFERENCES Colaborador(Id),
	FOREIGN KEY(IdCategoriaAtivos) REFERENCES CategoriaAtivos(Id),
	FOREIGN KEY(IdFabricante) REFERENCES Fabricante(Id),
	FOREIGN KEY(IdFornecedor) REFERENCES Fornecedor(Id),
	FOREIGN KEY(IdStatusAtivo) REFERENCES StatusAtivo(Id)
);
GO

CREATE TABLE LogAuditoria (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	IdUsuario INTEGER NOT NULL,
	TabelaAfetada VARCHAR(60) NOT NULL,
	IdRegistroAfetado INTEGER NOT NULL,
	Acao VARCHAR(100) NOT NULL,
	DataHoraAlteracao DATETIME NOT NULL,
	Detalhes VARCHAR(300),
	FOREIGN KEY(IdUsuario) REFERENCES Usuario(Id)
);
GO

CREATE TABLE TipoMovimentacao (
	Id SMALLINT NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(30) NOT NULL
);
GO

CREATE TABLE Movimentacao (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	IdTipoMovimentacao SMALLINT NOT NULL,
	IdUsuarioSolicitante INTEGER NOT NULL,
	IdMaterial INTEGER,
	IdAtivoTi INTEGER,
	IdColaboradorOrigem INTEGER,
	IdColaboradorDestino INTEGER,
	DataMovimentacao DATETIME NOT NULL,
	Justificativa VARCHAR(500) NOT NULL,
	Quantidade SMALLINT,
	FOREIGN KEY(IdTipoMovimentacao) REFERENCES TipoMovimentacao(Id),
	FOREIGN KEY(IdUsuarioSolicitante) REFERENCES Usuario(Id),
	FOREIGN KEY(IdMaterial) REFERENCES Material(Id),
	FOREIGN KEY(IdAtivoTi) REFERENCES AtivosTi(Id),
	FOREIGN KEY(IdColaboradorOrigem) REFERENCES Colaborador(Id),
	FOREIGN KEY(IdColaboradorDestino) REFERENCES Colaborador(Id)
);
GO

CREATE TABLE LicencaSoftware (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	NomeSoftware VARCHAR(255) NOT NULL,
	ChaveProduto VARCHAR(255) NOT NULL,
	DataExpiracao DATE NOT NULL
);
GO

CREATE TABLE LicencaAtivo (
	IdLicencaSoftware INTEGER NOT NULL,
	IdAtivoTi INTEGER NOT NULL,
	PRIMARY KEY(IdLicencaSoftware, IdAtivoTi),
	FOREIGN KEY(IdLicencaSoftware) REFERENCES LicencaSoftware(Id),
	FOREIGN KEY(IdAtivoTi) REFERENCES AtivosTi(Id)
);
GO

CREATE TABLE Manutencao (
	Id INTEGER NOT NULL IDENTITY PRIMARY KEY,
	IdAtivoTi INTEGER NOT NULL,
	TipoManutencao VARCHAR(20) NOT NULL,
	DataInicio DATE NOT NULL,
	DataFim DATE,
	DescricaoProblema VARCHAR(1000) NOT NULL,
	DescricaoServicoRealizado VARCHAR(1000),
	Custo DECIMAL(10,2) NOT NULL,
	FOREIGN KEY(IdAtivoTi) REFERENCES AtivosTi(Id)
);
GO